spring:
  config:
    activate:
      on-profile: local
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    url: ${PROD_DB_URL}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
---