server:
  servlet:
    context-path: /hackathon/api

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration

  application:
    name: hackathon
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  profiles:
    include:
      - database
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

oauth:
  kakao:
    client-id: ${OAUTH_KAKAO_CLIENT_ID}
    redirect-uri: ${OAUTH_KAKAO_REDIRECT_URI}
    token-uri: ${OAUTH_KAKAO_TOKEN_URI}
    user-info-uri: ${OAUTH_KAKAO_USER_INFO_URI}

jwt:
  secret: ${JWT_SECRET}

management:
  endpoint:
    metrics:
      enabled: false
    health:
      show-details: when-authorized

frontend:
  domain: mocacafe.vercel.app