name: Deploy to AWS EC2 using Docker

on:
  push:
    branches:
      - develop

env:
  DB_URL: ${{ secrets.DB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  PROD_DB_USERNAME: ${{ secrets.PROD_DB_USERNAME }}
  PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
  PROD_DB_URL: ${{ secrets.PROD_DB_URL }}
  OAUTH_KAKAO_CLIENT_ID: ${{ secrets.OAUTH_KAKAO_CLIENT_ID }}
  OAUTH_KAKAO_REDIRECT_URI: ${{ secrets.OAUTH_KAKAO_REDIRECT_URI }}
  OAUTH_KAKAO_TOKEN_URI: ${{ secrets.OAUTH_KAKAO_TOKEN_URI }}
  OAUTH_KAKAO_USER_INFO_URI: ${{ secrets.OAUTH_KAKAO_USER_INFO_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # JDK 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Gradle Build
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # DockerHub Push
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/likelion-app-dev .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/likelion-app-dev
  

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # AWS 배포
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd backend
            
            sudo bash -c 'cat > .env <<EOF
            DB_URL=${{ secrets.DB_URL }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            PROD_DB_URL=${{ secrets.PROD_DB_URL }}
            PROD_DB_USERNAME=${{ secrets.PROD_DB_USERNAME }}
            PROD_DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}
            OAUTH_KAKAO_CLIENT_ID=${{ secrets.OAUTH_KAKAO_CLIENT_ID }}
            OAUTH_KAKAO_REDIRECT_URI=${{ secrets.OAUTH_KAKAO_REDIRECT_URI }}
            OAUTH_KAKAO_TOKEN_URI=${{ secrets.OAUTH_KAKAO_TOKEN_URI }}
            OAUTH_KAKAO_USER_INFO_URI=${{ secrets.OAUTH_KAKAO_USER_INFO_URI }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOF'
  
            sudo docker-compose stop
            sudo docker-compose rm -f
            sudo docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/likelion-app-dev:latest
            sudo docker-compose up -d